version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch-network
  
  odoo-db:
    image: postgres:15
    ports:
      - 8070:5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
  
  odoo:
    image: odoo:17
    user: root
    # TODO: should only be run first time
    # command: -- --init base --database odoo --without-demo all
    depends_on:
      - odoo-db
    ports:
      - 8069:8069
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      # - odoo-data:/var/lib/odoo
      - ./odoo-data:/var/lib/odoo

volumes:
  elasticsearch-data:
  odoo-db-data:
  odoo-data:

networks:
  elasticsearch-network:
